package com.project.capstone.exchangesystem.constants;

public class AppStatus {
    public static final int ITEM_CREATE_ACTION = 0;
    public static final int ITEM_UPDATE_ACTION = 1;
    public static final int DONATION_CREATE_ACTION = 2;
    public static final int DONATION_UPDATE_ACTION = 3;
    public static final int USER_UPDATE_ACTION = 4;
    public static final int EXTERNAL_STORAGE_REQUEST = 0;
    public static final int CAMERA_REQUEST = 1;
    public static final int GALLERY_REQUEST = 2;
    public static final int CATEGORY_REQUEST = 3;
    public static final int CHANGE_IMAGE_FLAG = 0;
    public static final int ADD_IMAGE_FLAG = 1;
    public static final int DONATE_ACTIVITY_IMAGE_FLAG = 2;
    public static final int TRANSACTION_DONATIOM = 3;
    public static final int LOGIN_REMINDER = 0;
    public static final String ITEM_ENABLE = "1";
    public static final String ITEM_FRAGMENT_FLAG = "0";
    public static final String DONATION_FRAGMENT_FLAG = "1";
    public static final String NOTIFICATION_FRAGMENT_FLAG = "2";
    public static final String PROFILE_FRAGMENT_FLAG = "3";
    public static final String USER_DISABLE = "0";
    public static final String USER_ENABLE = "1";
    public static final int CHOOSE_IMAGE_OPTION = 0;
    public static final int CAPTURE_IMAGE_OPTION = 1;
    public static final int DELETE_IMAGE_OPTION = 2;
    public static final int CANCEL_IMAGE_OPTION = 3;
    public static final String TRANSACTION_SEND = "1";
    public static final String TRANSACTION_DONE = "2";
    public static final String TRANSACTION_DONATED = "3";
    public static final String TRANSACTION_RESEND = "4";
    public static final int SEND_MSG = 0;
    public static final int RECEIVE_MSG = 1;
    public static final String DISABLED_DONATION_POST = "0";
    public static final int USER_ACCEPTED_TRADE = 1;
    public static final int USER_ACCEPTED_TRADE_MESSAGE = -1;
    public static final int USER_CANCELED_TRADE_CONFIRM_MESSAGE = -2;
    public static final int USER_RESET_TRADE_MESSAGE = -3;
    public static final int TRADE_DONE_MESSAGE = -4;
    public static final int USER_ADDED_ITEM_MESSAGE = -5;
    public static final int USER_REMOVED_ITEM_MESSAGE = -6;
}
